devanooga/devanooga.com

- _includes/ga.html
- _layouts/default.html
> Add google analytics

- Gemfile
- Gemfile.lock
- _config.yml
https://deploy-preview-29--devanooga.netlify.com/sitemap.xml
Resolves #16
> Add sitemap support

- _includes/navigation.html
- _pages/coc.md
- _pages/contact.html
- _pages/members.md
- _pages/open-source.md
- _pages/slack.md
- _sass/_base.scss
- _sass/_header.scss
- _sass/_layout.scss
- _sass/_navigation.scss
Implements idea discussed in #37.
Navigation is now grouped into two groups.
> Nav groups

- _pages/coc.md
As suggested by @camilopayan on #36.
> Add administrators

- _sass/_header.scss
- _sass/_navigation.scss
Nav group 2 padding was off. Header bg color was too translucent (rendering nav text illegible in some cases).
> Miscellaneous header/nav tweaks

- _layouts/channel.html
- _pages/channels.html
- _pages/channels/dotnet.md
- _pages/channels/homelab.md
If I'm doing Jekyll wrong feel free to hit me over the head with a stick
resolves #17
> Basic channel support and a couple small channel pages

- _pages/channels/ham.md
Creates a channel page for `#ham`
> Ham channel

- _pages/channels/ham.md
Added a "Getting On the Air" section for basic info
> Ham channel improvements

- _collections/members/bobby_brb3.yml
> Add myself to the members page

- _pages/channels/ham.md
> Add Local Amateur Radio Clubs section to the #ham channel page

- readme.md
Also a bit clearer instructions here and there.
> Update readme with new profile properties

- _collections/members/digdog.yml
- _collections/members/patriotbob.yml
- _collections/members/tmbeihl.yml
DO NOT MERGE YET
Got a 3rd person I'll probably add once they hand me the relevant info.
> Adding Members To Member List

- _collections/members/tyler.malone.yml
> my profile

- _includes/header.html
- _includes/navigation.html
- _layouts/default.html
As opposed to loading the nav near the footer and moving it up.
> Load navigation inside the header

- _pages/contact.html
No more submitting empty contact-us forms
> Made fields on contact-us form required

- _pages/contact.html
- _sass/_form.scss
Fixes #70 and somewhat fixes #69
> Somewhat better contact page

- _pages/contact.html
- _sass/_form.scss
This improves on @StrangeWill’s work a bit by darkening the input borders (for contrast) and autofocusing on the first field.
I would have pointed this out on his PR, but  
~it was merged willy nilly~  
~my approval was not requested~  
~I get no respect~  
it was merged before I could take a look at it.
> Darken input borders; autofocus first field

- _collections/members/neomachina2011.md
Added myself, Daniel Hampton (neomachina2011), to the members
section/page.
> Added neomachina2011 to members

- _collections/members/bobby_brb3.md
> Add `writer` role to bobby_brb3

- _collections/members/kate.md
> Adds Kate to the members page

- Gemfile
- Gemfile.lock
- _config.yml
- _posts/2017-04-17-How-to-Post-to-the-Devanooga-Blog.md
- _posts/2017-04-22-Annoying-Mastodon-Users-with-a-Bot.md
Addresses #90 
This should not be merged until the "should dates be in the URL" discussion resolves in the issue.
> Update blog post URL live under the `blog` silo

- _collections/members/kate.md
Makes @kate an organizer and adds the `contributor` badge to her profile.
> Make kate organizer

- _includes/newsletter-signup.html
- _sass/_button.scss
- _sass/_form.scss
- css/main.scss
- index.html
This PR implements a newsletter signup form that gets submitted to MailChimp.
> Newsletter signup

- _sass/_form.scss
It does the thing. I’d like @Willamin to give this a once over as well (can’t add him as a Reviewer on here).
> Fix vertical alignment/wrapping in Safari, fixes #109

- readme.md
Changes the tool you use to get your gravatar hash from a third party tool to one from gravatar directly.
> Update gravatar hash tool

- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile
- _config.yml
- readme.md
- test/testBlogPosts.rb
Addresses #92 
We should add a few _basic_ tests in this PR just to have something passing, then add tests for pending PRs as applicable.
> Travis Config

- _includes/member.html
- _sass/_members.scss
Taking a stab at #111. This PR adds each member’s username below their picture.
> Member usernames

- _collections/members/joedodd.md
> Add joedodd.md

- _collections/members/godsmoon.md
> Add godsmoon member page

- _collections/members/willamin.md
> Add member page for willamin

- _collections/members/rob.md
> Add rob.md member page

- _collections/members/seabre.md
> Add member profile for Sean Brewer

- _collections/members/wvaladez.md
> Set quilt to true for wvaladez

- _collections/members/kate.md
Kate doesn't use twitter, and wants that link removed from her profile.
> Remove twitter profile from kate's profile

- _includes/scss/header.scss
- _includes/stylesheets-header.html
:sparkles: coolmeme.jpg :sparkles:
> Inline CSS In The Header

- _pages/coc.md
We'll discuss this prior to accepting this and I'll continue making changes.
* I don't like that administrators never "work alone", if no admin is online and something is violating policy, I'm removing it. Additionally I don't like the idea that if a decision is made, that we've already come to a consensus.
* Channel removal for dead/inactive channels (totally earmarked this).
Any other ideas?
> Add minor changes to CoC

- _includes/announcement.html
sets the hacknight date to two weeks from now
> update hacknight date

- _pages/channels/truebeginners.md
added a link to a 15 minute git tutorial to the truebeginners channel page
> added git tutorial to truebeginners channel page

- _includes/announcement.html
> Update next hacknight date to August 23rd

- _collections/members/andrew565.md
Andrew Steele shall be on the members page
> add andrew565 to members page

- _collections/members/jmanderson.md
> add James Anderson to members page

- _collections/members/agarzola.md
- _collections/members/strangewill.md
> Add keybase profile info

- _collections/members/shaun.md
> Add Shaun Patterson to members

- _includes/announcement.html
> Update hacknight date to November 15

- _pages/channels/ham.md
Here is some basic info for DMR. I also went ahead and created a Digital Radio section that could be populated with Fusion and Dstar stuff.
> add dmr info

- _includes/announcement.html
> update hacknight date to May 30 2018

- _pages/coc.md
- _sass/_code-of-conduct.scss
- css/footer.scss
> CoC changes about community notification on private decision making

- _includes/navigation.html
- _pages/blog.html
- _pages/opportunities.md
- _sass/_layout.scss
This PR addresses issue #108. It’s still a work in progress, as it could use some fleshing out and image love. Possibly blocked by #98, unless a better imagery idea comes along.
> Opportunities page

- _config.yml
- _pages/opportunities.md
- index.html
It does what the title says.
cc: @DigTK
> Spell out Tennessee and use non-breaking space

- _collections/outreach_members/sam.md
- _config.yml
- _includes/outreach_member.html
- _pages/members.html
- _pages/outreach.html
- _sass/_members.scss
Couldn't figure out how to add and include a new stylesheet and also couldn't figure out the nav sort methodology. Also am open to edits regarding frontend. Not my strong point
> WIP add outreach page

- _pages/coc.md
Fix typo in channel name for CoC changes section.
Update Bobby's handle in match current in Admins.
> Small CoC changes

- _collections/members/lizgaston.md
Hey!
Looks like you guys need some more women on your team...can I join the sweet quilt?
Cheers,
Liz
> added as member

- _includes/announcement.html
- _sass/_announcement.scss
Hello friends,
This PR adds an announcement to the front page of the site that tells users how they can get involved with out F@H team. This PR also adds a newline at the end of the file (courtesy of my text editor).
This PR is marked WIP because rubygems appears to be down so I cannot test it. For whatever reason, I deleted my local repo since my last PR. If anyone would like to pull this and test for yourself then that's fine. Otherwise, I'll wait until rubygems is back up before I remove the WIP
> add folding at home announcement

- _includes/footer.html
Adds a link to @ryanmaynard 's Brand Guide to the footer of all pages.
> Add footer link for the brand guide

- _pages/coc.md
Edit or change however desired. Once this is merged we can submit form to EFA
> Add EFF Frontier Alliance principles to bottom of CoC

- _posts/2021-10-21-How-I-Work-002-Mario-Ezra.md
- _posts/2021-10-28-How-I-Work-003-Bobby-Burden.md
- _posts/2021-11-04-How-I-Work-004-James-M-Anderson.md
- _posts/2021-11-11-How-I-Work-005-Sean-Brewer.md
- _posts/2021-11-18-How-I-Work-006-Keith-Nash.md
- _posts/2021-11-25-How-I-Work-007-Will-Lewis.md
- _posts/2021-12-01-How-I-Work-008-Ryan-Maynard.md
Dates are set for each Thursday
One suggestion was to add stock photos for when devices are mentioned but that can be done retroactively since they are scheduled so far out. 
Otherwise, I tried not to edit anyone's responses unless it was a clear spelling mistake.
> Devanooga "How I Work" series complete

- .github/workflows/nightly_deploy.yml
Fix location of `with` property. Should have been a child of the step, not the job.
> Update nightly_deploy job

- _collections/members/jasonfelix.md
> _collections/members/jasonfelix.md

- _collections/members/benlacroix.md
> New member request
